apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: apidesplieguedeaplicaciones-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_CONNECTION
          value: "sqlserver://sa:Expecto89$@host.docker.internal:1433?database=ResidenciasDB"
---
apiVersion: v1
kind: Service
metadata:
  name: go-api-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: go-api